### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by mina-sealink**
# Why
Release 1.4.0 so, need to update the changelog.

### CODE REVIEW

**Review by dwaring — APPROVED** [review]

**Comment by mnoack** [comment]
:+1: Although I think you might be able to do these changes without approval in future :)

**Comment by blaknite** [comment]
The repo has master protection turned on so no-one can commit or merge direct to master. This unfortunately means PRs for release branch merges.

**Comment by mnoack** [comment]
Whoa. I guess your process could still allow self-merging in release only changes then :)

**Comment by mnoack** [comment]
Unless that is also restricted at the repo level (e.g. all PR's require 1 other approver) :)

**Comment by blaknite** [comment]
Yeah it's at the repo level :(

**Pull request merged**
